### ISSUE TITLE
Visual Issues after UI refactoring (branch develop)

### ISSUE THREAD

**Issue by amedvedchuk** [xm-online/xm-webapp#217]
1. На стандартной форме создания сущности лишняя кнопка
![image](https://user-images.githubusercontent.com/10553379/74742029-91886b80-5266-11ea-8b68-ade935a540b6.png)
2. На форме смены стейтов - кнопки не в цветах темы
![image](https://user-images.githubusercontent.com/10553379/74742054-9d742d80-5266-11ea-94bb-92fd1c89741a.png)
3. Поехали стили иконок при смене стейтов (view - Compact)
![image](https://user-images.githubusercontent.com/10553379/74742070-a82ec280-5266-11ea-88ed-cb1fd61af911.png)
4. Кнопка не в стиле темы
![image](https://user-images.githubusercontent.com/10553379/74742097-b2e95780-5266-11ea-891f-6135107e7881.png)

**Comment by Kaskyi** [comment]
4. done

**Comment by Kaskyi** [comment]
All dialog windows were modified according to https://material.io/components/dialogs/
