### ISSUE TITLE
Missed xm-powered-by component in the develop branch

### ISSUE THREAD

**Issue by lkozina** [xm-online/xm-webapp#612]
If you have the following configuration in the UI settings:

```
poweredBy:
    redirectUrl: "https://www.xm-online.com"
    imageUrl: "../assets/img/logo-xm-online.png"
```  
The system doesn't show it in the develop branch features. Seems we missed this component.

![master](https://user-images.githubusercontent.com/25796355/89334684-923f7d80-d69f-11ea-9fde-e9f9d02cbe86.png)
![develop](https://user-images.githubusercontent.com/25796355/89334703-979cc800-d69f-11ea-909b-2769a54e9343.png)

**Comment by andrewkikot** [comment]
in progress on this...

**Comment by andrewkikot** [comment]
https://github.com/xm-online/xm-webapp/pull/616

**Comment by andrewkikot** [comment]
fixed in develop
