### ISSUE TITLE
The issue with showing titles in applications while pushing on 3 dots in the list

### ISSUE THREAD

**Issue by lkozina** [xm-online/xm-webapp#614]
Go to the Application and choose any entity.
Go to the list of entities and push on 3 dots.

As a result, the system shows titles for each item. Please see attached screens below:
**MASTER:**
![application3dots-master](https://user-images.githubusercontent.com/25796355/89336999-f1eb5800-d6a2-11ea-8717-146315896cfc.png)
**DEVELOP:**
![appliation3dots-develop](https://user-images.githubusercontent.com/25796355/89337042-fdd71a00-d6a2-11ea-9c0f-c5dccadefb81.png)

Please look into this and provide the fixes.

**Comment by andrewkikot** [comment]
fixed in develop
