### ISSUE TITLE
Administration: missed fields on the creation user form

### ISSUE THREAD

**Issue by lkozina** [xm-online/xm-webapp#618]
**Steps to reproduce:**
1) Go to the Administration -> User management tab.
2) Click on the + button to create a new user.

**Actual result:** Missed last name, role, language, activated, auto-logout fields on the form.
**DEVELOP:**
![create-user-develop](https://user-images.githubusercontent.com/25796355/89403177-98c20980-d720-11ea-80f7-3075180150f4.png)

**Expected result:** The form contains all fields as shown below.
**MASTER:**
![create-user-master](https://user-images.githubusercontent.com/25796355/89403195-9f508100-d720-11ea-9e2b-d065889fef2c.png)

**Comment by Kaskyi** [comment]
my
