### ISSUE TITLE
Administration: missed functionality to sort by default fields

### ISSUE THREAD

**Issue by lkozina** [xm-online/xm-webapp#620]
**Steps to reproduce:**

Go to the Administration -> Roles Management tab.

**Actual result:** Missed ability to sort by default fields in the list.
**DEVELOP:**
![sorting-by-fields-develop](https://user-images.githubusercontent.com/25796355/89411789-ac746c80-d72e-11ea-8730-8e9552df0cec.png)

**Expected result:** System shows an ability to sort by default fields in the list.
**MASTER:**
![sorting-by-fields-master](https://user-images.githubusercontent.com/25796355/89411845-c4e48700-d72e-11ea-89bc-43388b8d8b0c.png)

Please note that in develop branch sorting ability is missed in the following tabs:
- Roles Matrix;
- User Management;
- Client Management.

**Comment by andrewkikot** [comment]
all of these three tables should migrate on mat-tables...
