### ISSUE TITLE
Applications: Issue with entity saving that contains multilingual input

### ISSUE THREAD

**Issue by lkozina** [xm-online/xm-webapp#623]
**WHERE YOU CAN REPLICATE:** tenant/application/DEVELOP-MULTI-LANG

**Steps to reproduce:**

Go to the Applications and choose an appropriate entity application on the menu.
Push on the + button to create a new one.
Fill in data form and save changes.

**Actual result:** System doesn't allow to save entity that contains multilingual input
![multilingual-input-develop](https://user-images.githubusercontent.com/25796355/89431012-0df50500-d748-11ea-9854-829a07a78c75.png)

**Expected result:** System allows saving entity with multilingual input

**Comment by andrewkikot** [comment]
https://github.com/xm-online/xm-webapp/pull/681
