### ISSUE TITLE
Applications: Missed new functionality for ext-select component from master branch

### ISSUE THREAD

**Issue by lkozina** [xm-online/xm-webapp#624]
**WHERE YOU CAN REPLICATE:** tenant/application/DEVELOP

**Steps to reproduce:**

Go to the Applications and choose an appropriate entity application on the menu.
Go into details of entity record.

**Actual result:** System doesn't show a new ability to go into details of the entity selected in the ext-select component.
**DEVELOP**
![ext-select-develop](https://user-images.githubusercontent.com/25796355/89432231-88725480-d749-11ea-8c51-f3d5927ae79c.png)

**Expected result:** System shows a new ability to go into details of the entity selected in the ext-select component
**MASTER**
![ext-select-master](https://user-images.githubusercontent.com/25796355/89431941-37626080-d749-11ea-9a2e-40be1b7174f5.png)

**Comment by andrewkikot** [comment]
fixed in develop
