### ISSUE TITLE
Search: Page is reloaded after entering value

### ISSUE THREAD

**Issue by lkozina** [xm-online/xm-webapp#627]
**WHERE YOU CAN REPLICATE:** tenant/application/DEVELOP

**Steps to reproduce:**

Go to the system and enter a value in the search field.
Push enter.

**Actual result:** The system reloads page after click enter. Also, redirects on /application/search?
**DEVELOP**
![search-develop](https://user-images.githubusercontent.com/25796355/89442394-6ed80980-d757-11ea-8020-2e09213db169.png)

**Comment by andrewkikot** [comment]
taking this one

**Comment by andrewkikot** [comment]
fixed in develop
