### ISSUE TITLE
Paginator: Customize the paginator to one mode

### ISSUE THREAD

**Issue by lkozina** [xm-online/xm-webapp#638]
**WHERE YOU CAN REPLICATE:** tenant/application/DEVELOP

**Steps to reproduce:**

Go to the Applications and choose an appropriate entity application on the menu.

**Actual result:** System displays two different configurations to show item per page
**DEVELOP:**
![paginator-develop-apps](https://user-images.githubusercontent.com/25796355/89644725-29cfe680-d8c1-11ea-9472-59d86f714377.png)

![paginator-develop-roles](https://user-images.githubusercontent.com/25796355/89644738-2f2d3100-d8c1-11ea-9838-996953579a4f.png)

The same behavior is on the Administration chapter for the following menu items as the Roles Management, Roles Matrix, User Management, etc.

**Expected result:** System displays paginator regarding Angular specification. See example [here](https://material.angular.io/components/paginator/examples)

**Comment by andrewkikot** [comment]
also, roles inner tables should miograte on mat-tables...
