### ISSUE TITLE
Widgets: MD widget full-size issue

### ISSUE THREAD

**Issue by lkozina** [xm-online/xm-webapp#639]
**WHERE YOU CAN REPLICATE:** tenant/dashboard/1102

**Steps to reproduce:**

Go to the Dashboards and choose an appropriate dashboard on the menu.
Push on the full-size mode in widget details.

**Actual result:** The full-size mode isn't working properly in md widget.
**DEVELOP:**
![md-fullsize-develop](https://user-images.githubusercontent.com/25796355/89646310-3a359080-d8c4-11ea-99f3-fb6bf0656f80.png)
**Expected result:** The shown in the screen below.
**MASTER:**
![md-fulsize-master](https://user-images.githubusercontent.com/25796355/89646477-84b70d00-d8c4-11ea-8c64-a789ba4de9c2.png)

**Comment by andrewkikot** [comment]
remove index.html dependencie and move to     "@covalent/text-editor": "2.1.0",
