### ISSUE TITLE
Nothing happens when trying to view notification list

### ISSUE THREAD

**Issue by ATaisiia** [xm-online/xm-webapp#660]
WHERE YOU CAN REPLICATE: anywhere

**Steps to reproduce:**
![01](https://user-images.githubusercontent.com/69633073/90135369-3a79d400-dd7b-11ea-861b-35ee982e7082.png)
Click on the notification bell

**Actual result:**
Nothing happens

**Expected result:**
Notification list appears

**Comment by andrewkikot** [comment]
Not sure, if described use case is valid... becouse there are no notifications near the bell on screen.

**Comment by andrewkikot** [comment]
@lkozina, I believe, that valid use case was show dropdown if there are available notifications, isn't it?

**Comment by lkozina** [comment]
Sure, @andrewkikot 
In the master branch, we have ability to see the count of notification and push on the bell to get details. Please find the screenshot with details below:
![master-notifications](https://user-images.githubusercontent.com/25796355/90150235-2095bc80-dd8e-11ea-8d29-2c40e2390f0d.png)
