### ISSUE TITLE
Scroll from the main page does not work for modal window

### ISSUE THREAD

**Issue by ATaisiia** [xm-online/xm-webapp#665]
WHERE YOU CAN REPLICATE: application/ACCOUNT

**Steps to reproduce::**
1. Open the user
2. Reduce the window size (930 * 615)
3. Add new Link

**Actual result:**
The "Cancel" button is not visible (there is a scroll, but it does not apply to the window that appears)
![05 (2)](https://user-images.githubusercontent.com/69633073/90156888-b4b75200-dd95-11ea-90bc-b4db0d0f9de4.jpg)

**Expected Result:**
Scrolling is applied to the window that appears
![04 (2)](https://user-images.githubusercontent.com/69633073/90156900-b8e36f80-dd95-11ea-9ddb-fe5f2666c0f4.jpg)

**Comment by andrewkikot** [comment]
It looks like this PR solves the issue. Waitng for merge...
https://github.com/xm-online/xm-webapp/pull/657/files
