### ISSUE TITLE
No sort icon

### ISSUE THREAD

**Issue by ATaisiia** [xm-online/xm-webapp#666]
WHERE YOU CAN REPLICATE: administration/roles-matrix

**Steps to reproduce:**
1. Open page

**Actual result:**
There is no sort icon for "Privilege key"
![13](https://user-images.githubusercontent.com/69633073/90159688-6dcb5b80-dd99-11ea-986d-9d19fd0a5b62.jpg)

**Expected result:**
There is sort icon for "Privilege key"
![013](https://user-images.githubusercontent.com/69633073/90159704-7328a600-dd99-11ea-889d-019b3b9cae7f.jpg)

**Comment by andrewkikot** [comment]
This should be moved on mat-tables... 
Work in progress in this brunch https://github.com/xm-online/xm-webapp/pull/671
