### ISSUE TITLE
Application: Edit the "Account" page

### ISSUE THREAD

**Issue by ATaisiia** [xm-online/xm-webapp#713]
WHERE YOU CAN REPLICATE: application/ACCOUNT

### TC-01
**Steps to reproduce:**

1. Open Application - Account

**Expected result:**
Raise the filtration block higher

### TC-02
**Steps to reproduce:**

1. Open Application - Account

**Expected result:**
Add design to filtration block

### TC-03
**Steps to reproduce:**

1. Open Application - Account
2. Press the button "Edit panel"

**Expected result:**
The account name does not overlap the icon

![049](https://user-images.githubusercontent.com/69633073/91539917-be5ac100-e922-11ea-9cb9-f98273b1de55.jpg)

**Comment by andrewkikot** [comment]
TC-1, TC-2 - ok

I believe, TC-2 related to this issue:
https://github.com/xm-online/xm-webapp/issues/707
so, it's out of scope for this particular issue...

**Comment by lkozina** [comment]
rejected
