### ISSUE TITLE
Blue light when selecting options

### ISSUE THREAD

**Issue by ATaisiia** [xm-online/xm-webapp#735]
WHERE YOU CAN REPLICATE: application/DEMO

### ТС-01
**Steps to reproduce:**

1. Open Application - DEMO
2. Click on three dots

**Actual result:**
The selected option is highlighted in blue

![Снимок экрана 2020-09-08 в 16 35 11](https://user-images.githubusercontent.com/69633073/92499406-7ed68380-f204-11ea-8222-65dfab84d5a9.jpg)

### ТС-02
**Steps to reproduce:**

1. Open Application - DEMO
2. Open entity
3. Add tag

**Actual result:**
The "Tag" field is highlighted in blue

![Снимок экрана 2020-09-08 в 16 37 04](https://user-images.githubusercontent.com/69633073/92498921-e6d89a00-f203-11ea-89af-f75060f32d9f.png)

**Comment by lkozina** [comment]
Fixed
