### ISSUE TITLE
Remove unnecessary strip

### ISSUE THREAD

**Issue by ATaisiia** [xm-online/xm-webapp#736]
WHERE YOU CAN REPLICATE: application/DEMO

**Steps to reproduce:**

1. Open Application - DEMO
2. Open entity
3. Add an account

**Actual result:**
We see an unnecessary strip
![Снимок экрана 2020-09-08 в 16 38 56](https://user-images.githubusercontent.com/69633073/92503712-5782b500-f20a-11ea-8149-fea195103750.png)
![Снимок экрана 2020-09-08 в 16 43 55](https://user-images.githubusercontent.com/69633073/92503752-62d5e080-f20a-11ea-88cc-697fc53bdb25.jpg)
![Снимок экрана 2020-09-08 в 16 32 23](https://user-images.githubusercontent.com/69633073/92503757-636e7700-f20a-11ea-8667-0400b0a3577d.jpg)

**Expected Result:**
No stripes

![Снимок экрана 2020-09-08 в 16 32 54](https://user-images.githubusercontent.com/69633073/92503791-6c5f4880-f20a-11ea-9dd4-ace8e806a39e.png)

**Comment by lkozina** [comment]
The strip is still present on the Administration panel.

**Comment by lkozina** [comment]
Fixed.
